#!/bin/sh
################################################################################
#                                                                              #
#   Copyright (c) 2004                                                         #
#   RedPrairie Corporation                                                     #
#   All Rights Reserved                                                        #
#                                                                              #
#   The information in this file contains trade secrets and confidential       #
#   information which is the property of RedPrairie Corporation.               #
#                                                                              #
#   All trademarks, trade names, copyrights and other intellectual property    #
#   rights created, developed, embodied in or arising in connection with       #
#   this software shall remain the sole property of RedPrairie Corporation.    #
#                                                                              #
#   Copyright (c) RedPrairie Corporation, 2004                                 #
#   ALL RIGHTS RESERVED                                                        #
#                                                                              #
################################################################################

################################################################################
#                                                                              #
#       SCRIPT NAME:    createlinks                                            #
#                                                                              #
#       DESCRIPTION:    Script to create links to scripts in the               #
#                       server/source/bin/lis directory for development        #
#                       purposes.                                              #
#                                                                              #
#       APPLICATION:    DCS                                                    #
#                                                                              #
#    DATE     BY   PROJ   ID       DESCRIPTION                                 #
#    ======== ==== ====== ======== =============                               #
#    28/05/98 JH   DCS    NEW3375  Windows NT porting to Oracle 8              #
#    23/11/99 JH   DCS    NEW4609  Web front end background changes            #
#    09/03/00 JH   DCS    NEW4788  Web front end integration                   #
#    12/02/04 RMW  DCS    NEW7180  Scripting linking of OBR files.             #
#    11/11/10 SL   DCS    DSP3444  Added runrobotbenchmark                     #
#    15/12/11 JH   DCS    DSP1402  Browser rdt changes                         #
################################################################################

PROG="`basename $0`"
CLEANONLY="FALSE"
VERBOSE="FALSE"

usage()
{
	echo ""
	echo "Usage: $PROG [options]"
	echo ""
	echo "[-c]  Only clean development scripts from \$HOME/bin directory"
	echo "[-v]  Output what files are being processed"
	echo ""
}

create_link()
{
	#
	# Remove existing link & recreate
	#

	if [ "$VERBOSE" = "TRUE" -a -f "$1" ]
	then
		echo "createlinks: removing $1"
	fi

	rm -f $1

	if [ "$CLEANONLY" = "TRUE" ]
	then
		return
	fi

	if [ -f "$DCS/server/source/bin/lis/$1" ]
	then
		if [ "$MTYPE" = "WNT" ]
		then
			if [ "$VERBOSE" = "TRUE" ]
			then
				echo "createlinks: copying $DCS/server/source/bin/lis/$1"
			fi
			
			cp $DCS/server/source/bin/lis/$1 $1
		else
			if [ "$VERBOSE" = "TRUE" ]
			then
				echo "createlinks: linking $DCS/server/source/bin/lis/$1"
			fi

			ln -s $DCS/server/source/bin/lis/$1 $1
		fi
	fi
}

initialise()
{
	if [ ! -d "$DCS" ]
	then
		echo ""
		echo "$PROG: \$DCS not set to valid directory !"
		echo ""
		exit 1
	fi

	if [ "$MTYPE" = "WNT" ]
	then
		EXE=".exe"
	else
		EXE=""
	fi
}

initialise

while getopts cv? 2> /dev/null ARG
do
	case $ARG in
		c) 	CLEANONLY="TRUE";;
			
		v) 	VERBOSE="TRUE";;

		?)	usage
			exit 1;;
	esac	
done

if [ "$DCS/server/source/bin/lis" = "`pwd`" ]
then
	echo ""
	echo "$PROG: Cannot be run from $DCS/server/source/bin/lis !"
	echo ""
	exit 1
fi

create_link addfunctionaccess
create_link builddbdirs
create_link builddcs
create_link buildincludes
create_link buildjasperreports
create_link buildlang$EXE
create_link buildwebhelp
create_link checkhelpfiles
create_link checkinterfaces
create_link checkjasperfiles
create_link checksystemprofile
create_link datagen$EXE
create_link deletesingleclient
create_link deletesingleowner
create_link deletesinglesite
create_link makelive
create_link makelivepruner
create_link runcrstriptoremovecrs
create_link runrobotbenchmark

if [ "$APPLICATION_NAME" = "WMS" ]
then
	create_link buildrdt
	create_link buildrdtscr$EXE
	create_link buildreport
	create_link generateinterfacelibrary
	create_link scramble$EXE
	create_link generatetabledefinitionhtml
	create_link scheduler.sh
	create_link checkrdtfrmfieldtexts
fi

exit 0

