#!/bin/sh

#
# For updating main area on server for clean build.
#

cd $DCS

find . -name afiedt.buf -print | xargs rm -f
find . -name sqlnet.log -print | xargs rm -f
find . -name jim.tmp -print | xargs rm -f
find . -name rob.tmp -print | xargs rm -f
find . -name ".#*" -print | xargs rm -f

$DCS/server/source/bin/lis/buildincludes -c

echo ""

cvs -q update -d -P 2>&1 | \
	grep -v sv_se | \
	grep -v fr_fr | \
	grep -v nl_nl | \
	grep -v zh_cn | \
	grep -v buildinformation | \
	grep -v DatabaseConstant

echo ""
echo "Function access changes..."

FAOLD="$HOME/dcs/1function_access.dat.old"
FANEW="$DCS/server/data_takeon/lis/1function_access.dat"

if [ -f "$FAOLD" ]
then
	diff $FAOLD $FANEW
fi

cp $FANEW $FAOLD

echo ""
echo "Language text changes..."

FAOLD="$HOME/dcs/en_gb.t.old"
FANEW="$DCS/server/data_takeon/lis/en_gb.t"

if [ -f "$FAOLD" ]
then
	diff $FAOLD $FANEW
fi

cp $FANEW $FAOLD

echo ""

