#!/bin/bash

# build
cd $LUCAS_HOME
mvn clean install -f lucas-parent/pom.xml
mvn clean install -DskipTests=true -f lucas-parent/pom.xml -Pall

# run test
#To build the code with unit tests, you must specify the encryption key as below:
mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall


# To run unit tests and functional tests, issue:
 mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall,alltests

# To run unit tests and functional tests AND run liquibase scripts, issue:
mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall,alltests -Dskip.liquibase=false -Dliquibase.password=password

# To run unit tests and functional tests AND run liquibase scripts, and number of threads=50 issue:
mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall,alltests -Dskip.liquibase=false -Dliquibase.password=password -Dlucas.mq.queue.capacity=50

# To run unit tests and functional tests AND run liquibase scripts, issue: (Running locally against remote api server)
mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall,dev,alltests -Dskip.liquibase=false -Dliquibase.password=l00casd3vdbus3r -Dlucas.mq.host=54.87.153.50


# To run unit tests and functional tests AND run liquibase scripts, issue: (Running locally against remote api server with rabbitMQ details)
mvn clean install -DLUCAS_ENCRYPTION_PASSWORD=Hn4UKcorcdoQIFyby1BAs7ZQVmBm+NRk -f lucas-parent/pom.xml -Pall,dev,alltests -Dskip.liquibase=false -Dliquibase.password=l00casd3vdbus3r -Dlucas.mq.host=54.87.153.50 -Dlucas.mq.username=lucas -Dlucas.mq.pwd=lucas
