#!/bin/bash

#Cleans the working tree by recursively removing files that are not under version control, starting from the current directory.
#
#-d = Remove untracked directories in addition to untracked files -f = Force (might be not necessary depending on  clean.requireForce setting)
#
#Run git help clean to see the manual

cd $LUCAS_HOME

mv .idea /tmp/
git clean -df
mv /tmp/.idea .
