#! /bin/bash

LOCAL="FALSE"
AMD="TRUE"


usage()
{
	echo ""
	echo "Usage: $PROG [options]"
	echo ""
	echo "[-e EAI] "
	echo ""
	echo "[-l setup local] "
	echo ""
}
while getopts "el?" 2> /dev/null ARG
do
	case $ARG in

		e)	AMD="FALSE";;

		l)	LOCAL="TRUE";;

		?)	usage
			exit 1;;
	esac	
done

cd ~/bin/

if [ "$AMD" = "TRUE" ]
then
	if [ "$LOCAL" = "TRUE" ]
	then
		# local dev testing env
		cp CommonServicesLocal.js $LUCAS_HOME/lucas-amd/src/main/webapp/app/js/services/CommonServices.js
	else
		# put back the original
		cp CommonServicesDev.js $LUCAS_HOME/lucas-amd/src/main/webapp/app/js/services/CommonServices.js
	fi
else
	# EAI apps
	if [ "$LOCAL" = "TRUE" ]
	then
		# local dev testing env
		cp EAICommonServicesLocal.js $LUCAS_HOME/lucas-eai/src/main/webapp/common/services/CommonServices.js
	else
		# put back the original
		cp EAICommonServicesDev.js $LUCAS_HOME/lucas-eai/src/main/webapp/common/services/CommonServices.js
	fi
fi
