#!/bin/sh

ORASTATUS=""
LISTENERSTATUS=""

get_statuses()
{
	#
	# Work out if Oracle listener is up
	#
	lsnrctl status $ORACLE_SID >/dev/null

	if [ $? = 0 ]
	then
		LISTENERSTATUS="UP"
	else
		LISTENERSTATUS="DOWN"
	fi

	#
	# Work out if Oracle database is up
	#
	databaseup > /dev/null

	if [ "$?" = "1" ]
	then
		ORASTATUS="UP"
	else
		ORASTATUS="DOWN"
	fi
}

#
# Main
#

echo ""

get_statuses

if [ $LISTENERSTATUS != "UP" ]
then
	echo  "Starting Oracle listener..."

	lsnrctl start $ORACLE_SID > /dev/null 2>&1

	if [ $? != 0 ]
	then
		echo "Failed to start Oracle listener...abort"
		exit 1
	fi
else
	echo "Oracle listener is already running"
fi

if [ $ORASTATUS != "UP" ]
then
	if [ -x "$ORACLE_HOME/bin/svrmgrl$EXE" ]
	then
		DBADMIN="svrmgrl$EXE"
	else
		DBADMIN="sqlplus /nolog"
	fi

	echo "Starting Oracle database..."

	$DBADMIN << ! > /dev/null 2>&1
		connect $DCS_SYSINTERNAL as sysdba
		startup
!

	databaseup

	if [ $? = 0 ]
	then
		echo  "Failed to start Oracle database...abort"
		exit 1
	fi
else
	echo "Oracle database is already running"
fi

