--CREATE TABLESPACE "LUCAS_DATA" DATAFILE 'c:\<dbname>\LUCAS_DATA_01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE 2048M; 
CREATE TABLESPACE "LUCAS_DATA" DATAFILE '/apps/oracle/oradata/lucasware/LUCAS_DATA_01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE 2048M; 

CREATE TABLESPACE "LUCAS_INDEX" DATAFILE '/apps/oracle/oradata/lucasware/LUCAS_IDX_01.dbf' SIZE 100M REUSE AUTOEXTEND ON  MAXSIZE 2048M; 

CREATE TABLESPACE "LUCAS_LOB" DATAFILE '/apps/oracle/oradata/lucasware/LUCAS_LOB_01.dbf' SIZE 128M REUSE AUTOEXTEND ON MAXSIZE 4096M; 

CREATE ROLE LUCAS_SUPPORT_ROLE; 

CREATE PROFILE "NON_STD_APP" LIMIT CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME DEFAULT
SESSIONS_PER_USER DEFAULT
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_REUSE_MAX 13
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_LOCK_TIME UNLIMITED
FAILED_LOGIN_ATTEMPTS 5 ; 

create user lucasware identified by lucasware default tablespace lucas_data temporary tablespace temp; 
grant connect,resource to lucasware; 

--impdp userid=system directory=temp schemas=lucasware dumpfile=Lucase_export_lucasware.DMP log=impdp.log 

