#!/bin/bash

###
# Start New Feature and base your feature branch on develop 
# (git checkout -b feature/PHX-nn-a-short-description)
###

PROG="`basename $0`"
NEW_FEATURES=~/bin/new_features
DESC=""
MODULE_NUMBER=""
CREATE_NEW_BRANCH="FALSE"
FEATURE="TRUE"

usage()
{
	echo ""
	echo "Usage: $PROG [options]"
	echo ""
	echo "[-b bug]   Create / Checkout new BUG instead of default feature branch"
	echo ""
	echo "[-c create NEW]   Create / Checkout new feature/bug branch"
	echo ""
	echo "[-d desc]   Short description of new feature"
	echo ""
	echo "[-n module number]   Module number"
	echo ""
}


#
# Main program
#

while getopts "bcd:n:?" 2> /dev/null ARG
do
	case $ARG in

		b)	FEATURE="FALSE";;

		c)	CREATE_NEW_BRANCH="TRUE";;

		d)	DESC=$OPTARG;;

		n)	MODULE_NUMBER=$OPTARG;;

		?)	usage
			exit 1;;
	esac	
done

if [ "$DESC" = "" ]
then
        echo ""
        echo "$PROG: Short description is required !"
        echo ""
	usage
        exit 1
fi

if [ "$MODULE_NUMBER" = "" ]
then
        echo ""
        echo "$PROG: Module number is required !"
        echo ""
	usage
        exit 1
fi


cd $LUCAS_HOME
git fetch
git checkout develop
git rebase origin/develop

if [ "$CREATE_NEW_BRANCH" = "TRUE" ]
then
	if [ "$FEATURE" = "TRUE" ] 
	then
		echo "feature/PHX-$MODULE_NUMBER-$DESC" >> $NEW_FEATURES
		git checkout -b "feature/PHX-$MODULE_NUMBER-$DESC"
	else
		echo "bug/PHX-$MODULE_NUMBER-$DESC" >> $NEW_FEATURES
		git checkout -b "bug/PHX-$MODULE_NUMBER-$DESC"
	fi
else
	if [ "$FEATURE" = "TRUE" ] 
	then
		git checkout "feature/PHX-$MODULE_NUMBER-$DESC"
	else
		git checkout "bug/PHX-$MODULE_NUMBER-$DESC"
	fi
fi
