#!/bin/bash

###
# Start New Feature and base your feature branch on develop 
# (git checkout -b feature/PHX-nn-a-short-description)
###

PROG="`basename $0`"
NEW_FEATURES=~/bin/new_features
DESC=""
MODULE_NUMBER=""

usage()
{
	echo ""
	echo "Usage: $PROG [options]"
	echo ""
	echo "[-d desc]   Short description of new feature"
	echo ""
	echo "[-n module number]   Module number"
	echo ""
}


#
# Main program
#

while getopts "d:n:?" 2> /dev/null ARG
do
	case $ARG in

		d)	DESC=$OPTARG;;

		n)	MODULE_NUMBER=$OPTARG;;

		?)	usage
			exit 1;;
	esac	
done

if [ "$DESC" = "" ]
then
        echo ""
        echo "$PROG: Short description is required !"
        echo ""
	usage
        exit 1
fi

if [ "$MODULE_NUMBER" = "" ]
then
        echo ""
        echo "$PROG: Module number is required !"
        echo ""
	usage
        exit 1
fi


cd $LUCAS_HOME
echo "feature/PHX-$MODULE_NUMBER-$DESC" >> $NEW_FEATURES
git checkout -b "feature/PHX-$MODULE_NUMBER-$DESC"
