#!/bin/sh

APACHESTATUS=""
ORASTATUS=""
WEBSTATUS=""
APPSTATUS=""
LISTENERSTATUS=""
GATEWAY=""

get_statuses()
{
	#
	# Work out if Apache is up
	#

	APACHESTATUS=`pscmd -e | grep "httpd" | grep -i $APACHE_HOME | grep -v grep | grep -v sqldeveloper | grep -v Xvnc` >/dev/null

	if [ "$APACHESTATUS" != "" ]
	then
		APACHESTATUS="UP"
	else
		APACHESTATUS="DOWN"
	fi

	#
	# Work out if Oracle listener is up
	#

	lsnrctl status $ORACLE_SID >/dev/null

	if [ $? = 0 ]
	then
		LISTENERSTATUS="UP"
	else
		LISTENERSTATUS="DOWN"
	fi

	lsnrctl status dg4msql >/dev/null

	if [ $? = 0 ]
	then
		GATEWAY="UP"
	else
		GATEWAY="DOWN"
	fi
	#
	# Work out if Oracle database is up
	#

	databaseup > /dev/null

	if [ "$?" = "1" ]
	then
		ORASTATUS="UP"
	else
		ORASTATUS="DOWN"
	fi

	#
	# Work out if Application is up
	#

	sia -u >/dev/null

	if [ "$?" = "0" ]
	then
		APPSTATUS="UP"
	else
		APPSTATUS="DOWN"
	fi

	#
	# Work out if JBoss application server is up
	#

	WEBSTATUS=`pscmd -e | grep "org.jboss.Main \-c $APPS_PART" | grep -v grep`

	if [ "$WEBSTATUS" != "" ]
	then
		WEBSTATUS="UP"
	else
		WEBSTATUS="DOWN"
	fi
}

#
# Main
#

echo ""

get_statuses

if [ $APACHESTATUS != "UP" ]
then
	echo  "Starting Apache..."

	sudo rm -f $APACHE_HOME/logs/httpd.pid 2>/dev/null

	apachectl -u >/dev/null 2>&1

	if [ $? != 0 ]
	then
		echo "Failed to start Apache...abort"
		exit 1
	fi
else
	echo "Apache is already running"
fi

if [ $LISTENERSTATUS != "UP" ]
then
	echo  "Starting Oracle listener..."

	lsnrctl start $ORACLE_SID > /dev/null 2>&1

	if [ $? != 0 ]
	then
		echo "Failed to start Oracle listener...abort"
		exit 1
	fi
else
	echo "Oracle listener is already running"
fi

if [ $GATEWAY != "UP" ]
then
	echo  "Starting Gateway listener..."

	lsnrctl start dg4msql > /dev/null 2>&1

	if [ $? != 0 ]
	then
		echo "Failed to start Oracle gateway listener...abort"
		exit 1
	fi
else
	echo "Oracle gateway listener is already running"
fi

if [ $ORASTATUS != "UP" ]
then
	if [ -x "$ORACLE_HOME/bin/svrmgrl$EXE" ]
	then
		DBADMIN="svrmgrl$EXE"
	else
		DBADMIN="sqlplus /nolog"
	fi

	echo "Starting Oracle database..."

	$DBADMIN << ! > /dev/null 2>&1
		connect $DCS_SYSINTERNAL as sysdba
		startup
!

	databaseup

	if [ $? = 0 ]
	then
		echo  "Failed to start Oracle database...abort"
		exit 1
	fi
else
	echo "Oracle database is already running"
fi

if [ $APPSTATUS != "UP" ]
then
	echo "Starting Application..."

	appstart -y >/dev/null 2>&1

	if [ $? != 0 ]
	then
		echo  "Failed to start Application...abort"
		exit 1
	fi
else
	echo "Application is already running"
fi

if [ $WEBSTATUS != "UP" ]
then
	echo "Starting JBoss application server..."

	partitionctl -u >/dev/null 2>&1

	if [ $? != 0 ]
	then
		echo  "Failed to start JBoss application server...abort"
		exit 1
	fi
else
	echo "JBoss application server is already running"
fi

if [ "$DCS_DEVELOPER" = "YES" ]
then
	checkerrorlogs
else
	echo ""
fi

